language: node_js
node_js:
- 8.9.0
dist: trusty
addons:
  chrome: stable
branches:
  only:
  - develop
  - "/^feature\\/.*$/"
before_script:
- npm install -g angular-cli
script: "./build.sh"
notifications:
  slack:
    secure: "aRL0uFdBOKcSQ9kVgQsrBavAdK038rE7PJjD03yIdZ/7nPv6zd7mPEwfI/91pUUPziPdTGmHk+KKVettqYbhoasxR/TETm19rEwd64UmZFg3xkq7gXzCvZg4awqLXChwFFjRZnLqAczmqB2oeun3AHLlac0MBZAu5pJWIh3hYu41F1TwZYArn6uaOL9UgJH0LwMVjj7pXOjHudgxnEftw5e6u6LVQ/oJgBRxJrlvBqCzeG7SWUVu4kuonFZ+decjHcOw4OF8JtRCjt0SGUa9ezaTOPk2M2gLZ2vTR01imYjotXx6ELSzrcu0yGFdyj1TB5+s4/Fb5K4KDDOPaV7ge/HL6q4CIsMZgfd/WQJZ6RDvtFFyiqLkocQrbFvEMoXmkv08/d8sq+Jm/d5WWZYx8MehLX8dpeflyDZJ8B3g36XmpSzN8d3LvapUhFhDK/2gsnhWImJigj2I/7fBu8uMDapR0uBp9ilRWZXDk6tSUIZpHVEwWkCoVyR4mo7Scllmq66WORqwY0Ln7wgA7DUSnUVf8YrrB1FWE5gOM0P0ZnypBEs4BMxak1Be+UKf6vCXm3rZED+VN8LkhuqTywoQs9Fn16V9woOZvjFd4ttLkOjxVX+Te6QGxsYlr4j5EFccq8nvtXGdGujkr2Imd2bbSboFAnbYEA8qcnvt+1ngwxA="
    on_failure: always
    on_success: change
  email:
    on_failure: change
    on_success: change
